spring:
  data:
    mongodb:
      uri: mongodb+srv://jarvisroot:JarvisTest@jarvis-cluster0.dtma9kq.mongodb.net/megabloques_dev?retryWrites=true&w=majority&appName=Jarvis-Cluster0

server:
  port: 8080

logging:
  level:
    com.megabloques: DEBUG
