spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://jarvisroot:JarvisTest@jarvis-cluster0.dtma9kq.mongodb.net/megabloques_prod?retryWrites=true&w=majority&appName=Jarvis-Cluster0}

server:
  port: ${PORT:8080}

logging:
  level:
    com.megabloques: INFO
